package:
  name: muscle
  version: "5.3"

source:
  path: .

build:
  number: 0
  ignore_run_exports:
    - python
    - conda
    - r-base

requirements:
  build:
    - conda

about:
  home: https://drive5.com/muscle
  license: GPL-3.0-only
  summary: "Muscle is widely-used software for making multiple alignments of biological sequences."
  description: |
    Multiple sequence and structure alignment with top benchmark scores scalable to
    thousands of sequences. Generates replicate alignments, enabling assessment of
    downstream analyses such as trees and predicted structures.
  doc_url: https://drive5.com/muscle5/manual/
  dev_url: https://github.com/rcedgar/muscle

extra:
  recipe-maintainers:
    - Thomas1664
